Footer
dandelionadia/valley_of_art pull request #4
Opened 2021-12-14 07:49 UTC by dandelionadia

What was done: 
* adds footer
* fixes logo padding in the header on the sm

2021-12-14 11:00 UTC, kettanaito commented on src/components/Footer.jsx
> +        © 2022 Nadiia Ridko. All rights reserved.
You can also use `new Date().getFullYear()` to automatically display the current year in the copyright notice ;) 
```suggestion
        © {new Date().getFullYear()} Nadiia Ridko. All rights reserved.
```

2021-12-14 11:00 UTC, kettanaito commented on src/components/Footer.jsx
> +        hart ❤️).
```suggestion
        heart ❤️).
```
❤️

2021-12-14 11:00 UTC, kettanaito commented on src/components/Footer.jsx
> +        Made by Nadiia and Artem (You're always will have a special place in my
```suggestion
        Made by Nadiia and Artem (You will always have a special place in my
```

2021-12-14 11:01 UTC, kettanaito commented on src/components/Footer.jsx
> +        Made by Nadiia and Artem (You're always will have a special place in my
If you want, you can mention that it was designed by me.

2021-12-14 11:01 UTC, kettanaito requested changes
Just a few comments!

2021-12-15 07:18 UTC, dandelionadia commented on src/components/Footer.jsx
> +        hart ❤️).
😅

2021-12-15 07:18 UTC, dandelionadia commented on src/components/Footer.jsx
> +        Made by Nadiia and Artem (You're always will have a special place in my
😅

2021-12-15 15:41 UTC, kettanaito approved these changes
😗

2021-12-15 17:26 UTC, merged